//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sol_Biblioteca.Interfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sol_Biblioteca.Interfaces.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string btnBuscar_Text {
            get {
                return ResourceManager.GetString("btnBuscar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string btnCerrar_Text {
            get {
                return ResourceManager.GetString("btnCerrar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciar Mes Actual.
        /// </summary>
        internal static string btnDepreciar_Text {
            get {
                return ResourceManager.GetString("btnDepreciar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string btnEliminar_Text {
            get {
                return ResourceManager.GetString("btnEliminar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string btnGuardar_Text {
            get {
                return ResourceManager.GetString("btnGuardar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string btnModificar_Text {
            get {
                return ResourceManager.GetString("btnModificar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string btnNuevo_Text {
            get {
                return ResourceManager.GetString("btnNuevo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha:.
        /// </summary>
        internal static string lblFecha_Text {
            get {
                return ResourceManager.GetString("lblFecha_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número:.
        /// </summary>
        internal static string lblNumero_Text {
            get {
                return ResourceManager.GetString("lblNumero_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones:.
        /// </summary>
        internal static string lblObservaciones_Text {
            get {
                return ResourceManager.GetString("lblObservaciones_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable:.
        /// </summary>
        internal static string lblResponsable_Text {
            get {
                return ResourceManager.GetString("lblResponsable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de Depreciaciones de Activos.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
